### ISSUE TITLE
BUG: theo.registerFormat is not a function

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-tokens#1]
although the gulp tasks and relevant npm packages are taken from `vf-core` I am getting this error message when running `gulp tokens`

Full error is:

```
theo.registerFormat( "variables.scss",);
     ^

TypeError: theo.registerFormat is not a function
    at Object.<anonymous> (/Users/sr/Sites/EMBL/vf-tokens/gulpfile.js:99:6)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:175:63)
```

**Comment by sturobson** [comment]
I needed to make sure we were calling `gulp-theo` _and_ `theo` for this to work.

We also needed to include `gulp-rename`
